# Generated by Django 3.2 on 2021-04-29 21:49

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='blog')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
